name: Full EC2 WAR Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy WAR to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Upload and Deploy WAR
      run: |
        # Upload WAR to EC2
        scp -o StrictHostKeyChecking=no -i key.pem path/to/ACM-W.war ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/ACM-W.war

        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Remove old files if any
          sudo rm -rf /opt/tomcat/webapps/ACM-W /opt/tomcat/webapps/ACM-W.war

          # Move the new WAR file
          sudo mv /tmp/ACM-W.war /opt/tomcat/webapps/

          # Restart Tomcat
          sudo /opt/tomcat/bin/shutdown.sh
          sleep 5
          sudo nohup /opt/tomcat/bin/startup.sh &
        EOF
